import type {Ruleset} from '../../../lib/unpackRuleset.ts'

const makeImportMigration = (from: string, to: string) => {
  return {
    name: from,
    message: `Use ${to}`,
  }
}

export const eslintRules = (): Ruleset => {
  return {
    id: 'eslint',
    warn: {
      preferTemplate: [],
      operatorAssignment: [],
      objectShorthand: [],
      noUselessRename: [],
      noElseReturn: [],
      newCap: [],
      noEqNull: [],
      noExtendNative: [],
      noLonelyIf: [],
      noMultiAssign: [],
      noNestedTernary: [],
      noObjectConstructor: [],
      noUnderscoreDangle: {
        allow: ['__REDUX_DEVTOOLS_EXTENSION_COMPOSE__'],
      },
      noUnneededTernary: [],
      noWith: [],
      oneVar: 'never',
      preferConst: [],
      preferExponentiationOperator: [],
      sortVars: [],
      curly: 'all',
      getterReturn: {
        allowImplicit: true,
      },
      logicalAssignmentOperators: 'always',
      noArrayConstructor: [],
      noClassAssign: [],
      noCompareNegZero: [],
      noDuplicateImports: {
        allowSeparateTypeImports: true,
      },
      noRestrictedImports: [
        makeImportMigration('lodash', 'es-toolkit'),
        makeImportMigration('ensure-array', 'sure-array'),
        makeImportMigration('@absolunet/fsp', 'fs-extra'),
        makeImportMigration('@absolunet/fss', 'fs-extra'),
        makeImportMigration('opn', 'open'),
        makeImportMigration('pify', 'util.promisify'),
        makeImportMigration('fs/promises', 'fs-extra'),
        makeImportMigration('node:fs/promises', 'fs-extra'),
        makeImportMigration('execall', 'super-regex'),
        makeImportMigration('js-yaml', 'yaml'),
        makeImportMigration('jest', 'bun:test'),
        makeImportMigration('@types/jest', 'bun:test'),
        makeImportMigration('jest-extended', 'bun:test'),
        makeImportMigration('jest-light-runner', 'bun:test'),
        makeImportMigration('node:test', 'bun:test'),
        makeImportMigration('emp', 'fs-extra (emptyDir)'),
        makeImportMigration('ts-xor', 'Xor from type-fest'),
        makeImportMigration('delay', 'Bun.sleep() or Bun.sleepSync()'),
        makeImportMigration('lodash-es', 'es-toolkit'),
        makeImportMigration('winston', 'pino'),
        makeImportMigration('got', 'ky'),
        makeImportMigration('wrap-ansi', 'Bun.wrapAnsi()'),
        makeImportMigration('strip-ansi', 'Bun.stripAnsi()'),
        makeImportMigration('uuid', 'nanoid or crypto.randomUUID() or Bun.randomUUIDv7()'),
        makeImportMigration('string-width', 'Bun.stringWidth()'),
        makeImportMigration('babel', '@swc/core'),
        makeImportMigration('webpack', '@rspack/core or vite'),
        makeImportMigration('rollup', 'rolldown'),
      ],
      noExtraBind: [],
      noLossOfPrecision: [],
      noUselessComputedKey: [],
      noUselessReturn: [],
      preferNumericLiterals: [],
      preferObjectHasOwn: [],
      preferObjectSpread: [],
      useIsnan: [],
    },
    error: {
      noDupeArgs: [],
      noDupeClassMembers: [],
      noDupeElseIf: [],
      noDuplicateCase: [],
      noVar: [],
      validTypeof: [],
    },
  }
}
