import type {Ruleset} from 'lib/unpackRuleset.ts'

export const stylisticRules = (): Ruleset => ({
  id: 'stylistic',
  warn: {
    curlyNewline: [], // TODO: Migrate to list-style: https://eslint.style/rules/list-style
    typeNamedTupleSpacing: [],
    typeGenericSpacing: [],
    nonblockStatementBodyPosition: 'below',
    multilineTernary: 'never',
    blockSpacing: [],
    multilineCommentStyle: 'separate-lines',
    braceStyle: [],
    commaSpacing: [],
    functionCallSpacing: [],
    indent: [
      2,
      {
        ignoreComments: true,
      },
    ],
    keySpacing: [],
    keywordSpacing: [],
    objectCurlySpacing: [],
    paddingLineBetweenStatements: [
      {
        blankLine: 'never',
        prev: '*',
        next: '*',
      },
      {
        blankLine: 'any',
        prev: 'import',
        next: '*',
      },
      {
        blankLine: 'any',
        prev: '*',
        next: 'export',
      },
      {
        blankLine: 'any',
        prev: 'import',
        next: 'type',
      },
      {
        blankLine: 'any',
        prev: 'type',
        next: '*',
      },
      {
        blankLine: 'any',
        prev: '*',
        next: 'type',
      },
      {
        blankLine: 'any',
        prev: 'type',
        next: 'type',
      },
      {
        blankLine: 'any',
        prev: 'export',
        next: '*',
      },
    ],
    quotes: [
      'single',
      {
        avoidEscape: true,
      },
    ],
    spaceBeforeBlocks: [],
    spaceBeforeFunctionParen: {
      anonymous: 'always',
      named: 'never',
      asyncArrow: 'always',
    },
    spaceInfixOps: [],
    memberDelimiterStyle: {
      singleline: {
        delimiter: 'comma',
        requireLast: false,
      },
      multiline: {
        delimiter: 'none',
        requireLast: false,
      },
    },
    typeAnnotationSpacing: [],
    arrayBracketNewline: {
      multiline: true,
    },
    arrayBracketSpacing: [],
    arrayElementNewline: 'consistent',
    arrowParens: 'as-needed',
    arrowSpacing: [],
    commaDangle: {
      arrays: 'always-multiline',
      objects: 'always-multiline',
      imports: 'always-multiline',
      exports: 'always-multiline',
      functions: 'always-multiline',
      enums: 'always-multiline',
      generics: 'always-multiline',
      tuples: 'always-multiline',
    },
    commaStyle: [],
    computedPropertySpacing: [],
    dotLocation: 'property',
    eolLast: [],
    functionParenNewline: 'never',
    implicitArrowLinebreak: [],
    linebreakStyle: 'unix',
    newParens: 'never',
    noExtraParens: [],
    noFloatingDecimal: [],
    noMultipleEmptyLines: {
      max: 1,
      maxEOF: 1,
      maxBOF: 0,
    },
    noTabs: [],
    noTrailingSpaces: [],
    noWhitespaceBeforeProperty: [],
    objectCurlyNewline: {
      ObjectExpression: {
        consistent: true,
        minProperties: 2,
        multiline: true,
      },
      ObjectPattern: 'never',
      ImportDeclaration: 'never',
    },
    objectPropertyNewline: [],
    operatorLinebreak: 'before',
    paddedBlocks: 'never',
    quoteProps: 'as-needed',
    restSpreadSpacing: [],
    spaceInParens: [],
    spaceUnaryOps: [],
    spacedComment: [],
    switchColonSpacing: [],
    templateCurlySpacing: [],
    templateTagSpacing: [],
    yieldStarSpacing: [],
    functionCallArgumentNewline: 'never',
    generatorStarSpacing: [],
    maxStatementsPerLine: [],
    newlinePerChainedCall: [],
    noConfusingArrow: [],
    noMultiSpaces: [],
    semi: 'never',
  },
})
