import type {Ruleset} from '../../../lib/unpackRuleset.ts'

export const typescriptRules = (): Ruleset => {
  return {
    id: 'typescript',
    warn: {
      preferFunctionType: [],
      noWrapperObjectTypes: [],
      noExtraNonNullAssertion: [],
      noDuplicateTypeConstituents: [],
      banTsComment: {
        'ts-expect-error': {descriptionFormat: String.raw`^ +(ts\(\d+\)|TS\d+)( .+$|$)`},
        'ts-ignore': true,
        'ts-nocheck': false,
        'ts-check': false,
      },
      noBaseToString: [],
      noMisusedPromises: [],
      noNonNullAssertedNullishCoalescing: [],
      noNonNullAssertedOptionalChain: [],
      noRedundantTypeConstituents: [],
      noUnnecessaryBooleanLiteralCompare: [],
      noUnnecessaryCondition: {
        allowConstantLoopConditions: true,
      },
      noUnnecessaryQualifier: [],
      noUnnecessaryTypeArguments: [],
      noUnnecessaryTypeAssertion: [],
      noUnnecessaryTypeConstraint: [],
      noUnsafeArgument: [],
      noUnsafeAssignment: [],
      noUnsafeCall: [],
      noUnsafeDeclarationMerging: [],
      noUnsafeEnumComparison: [],
      noUnsafeMemberAccess: [],
      noUnsafeReturn: [],
      noUnsafeUnaryMinus: [],
      preferIncludes: [],
      preferOptionalChain: [],
      preferReduceTypeParameter: [],
      preferStringStartsEndsWith: [],
      restrictTemplateExpressions: [],
      unboundMethod: {
        ignoreStatic: true,
      },
      dotNotation: [],
      noArrayConstructor: [],
      noDupeClassMembers: [],
      noShadow: [],
      onlyThrowError: [],
      noUseBeforeDefine: [],
      noUselessConstructor: [],
      preferRegexpExec: [],
      requireArraySortCompare: [],
      returnAwait: [],
      arrayType: {
        default: 'generic',
      },
      classLiteralPropertyStyle: [],
      consistentGenericConstructors: [],
      consistentIndexedObjectStyle: [],
      consistentTypeAssertions: {
        assertionStyle: 'as',
        objectLiteralTypeAssertions: 'allow',
      },
      consistentTypeExports: [],
      consistentTypeImports: {
        prefer: 'type-imports',
        disallowTypeAnnotations: false,
        fixStyle: 'separate-type-imports',
      },
      methodSignatureStyle: [],
      noMeaninglessVoidOperator: [],
      noUnnecessaryTemplateExpression: [],
      preferAsConst: [],
      noDeprecated: [],
      noDuplicateEnumValues: [],
      noArrayDelete: [],
      noFloatingPromises: {
        ignoreVoid: false,
      },
      noImportTypeSideEffects: [],
      awaitThenable: [],
      noMisusedSpread: [],
      noUnnecessaryTypeConversion: [],
      noUnnecessaryTypeParameters: [],
      noUselessDefaultAssignment: [],
    },
  }
}
