import type {Ruleset} from '../../../lib/unpackRuleset.ts'

const makeImportMigration = (from: string, to: string) => {
  return {
    name: from,
    message: `Use ${to}`,
  }
}

export const typescriptRules = (): Ruleset => {
  return {
    id: 'typescript',
    warn: {
      preferFunctionType: [],
      noWrapperObjectTypes: [],
      noExtraNonNullAssertion: [],
      noDuplicateTypeConstituents: [],
      banTsComment: {
        'ts-expect-error': {descriptionFormat: String.raw`^ +(ts\(\d+\)|TS\d+)( .+$|$)`},
        'ts-ignore': true,
        'ts-nocheck': false,
        'ts-check': false,
      },
      noBaseToString: [],
      noMisusedPromises: [],
      noNonNullAssertedNullishCoalescing: [],
      noNonNullAssertedOptionalChain: [],
      noRedundantTypeConstituents: [],
      noUnnecessaryBooleanLiteralCompare: [],
      noUnnecessaryCondition: {
        allowConstantLoopConditions: true,
      },
      noUnnecessaryQualifier: [],
      noUnnecessaryTypeArguments: [],
      noUnnecessaryTypeAssertion: [],
      noUnnecessaryTypeConstraint: [],
      noUnsafeArgument: [],
      noUnsafeAssignment: [],
      noUnsafeCall: [],
      noUnsafeDeclarationMerging: [],
      noUnsafeEnumComparison: [],
      noUnsafeMemberAccess: [],
      noUnsafeReturn: [],
      noUnsafeUnaryMinus: [],
      preferIncludes: [],
      preferOptionalChain: [],
      preferReduceTypeParameter: [],
      preferStringStartsEndsWith: [],
      restrictTemplateExpressions: [],
      unboundMethod: {
        ignoreStatic: true,
      },
      dotNotation: [],
      noArrayConstructor: [],
      noDupeClassMembers: [],
      noRestrictedImports: [
        makeImportMigration('lodash', 'es-toolkit'),
        makeImportMigration('ensure-array', 'sure-array'),
        makeImportMigration('@absolunet/fsp', 'fs-extra'),
        makeImportMigration('@absolunet/fss', 'fs-extra'),
        makeImportMigration('opn', 'open'),
        makeImportMigration('pify', 'util.promisify'),
        makeImportMigration('fs/promises', 'fs-extra'),
        makeImportMigration('node:fs/promises', 'fs-extra'),
        makeImportMigration('execall', 'super-regex'),
        makeImportMigration('js-yaml', 'yaml'),
        makeImportMigration('jest', 'bun:test'),
        makeImportMigration('@types/jest', 'bun:test'),
        makeImportMigration('jest-extended', 'bun:test'),
        makeImportMigration('jest-light-runner', 'bun:test'),
        makeImportMigration('node:test', 'bun:test'),
        makeImportMigration('emp', 'fs-extra (emptyDir)'),
        makeImportMigration('rollup', 'Arrayable from type-fest'),
        makeImportMigration('ts-xor', 'Xor from type-fest'),
        makeImportMigration('delay', 'Bun.sleep() or Bun.sleepSync()'),
        makeImportMigration('lodash-es', 'es-toolkit'),
        makeImportMigration('winston', 'pino'),
        makeImportMigration('got', 'ky'),
        makeImportMigration('wrap-ansi', 'Bun.wrapAnsi()'),
        makeImportMigration('strip-ansi', 'Bun.stripAnsi()'),
        makeImportMigration('uuid', 'nanoid or crypto.randomUUID() or Bun.randomUUIDv7()'),
        makeImportMigration('string-width', 'Bun.stringWidth()'),
      ],
      noShadow: [],
      onlyThrowError: [],
      noUseBeforeDefine: [],
      noUselessConstructor: [],
      preferRegexpExec: [],
      requireArraySortCompare: [],
      returnAwait: [],
      arrayType: {
        default: 'generic',
      },
      classLiteralPropertyStyle: [],
      consistentGenericConstructors: [],
      consistentIndexedObjectStyle: [],
      consistentTypeAssertions: {
        assertionStyle: 'as',
        objectLiteralTypeAssertions: 'allow',
      },
      consistentTypeExports: [],
      consistentTypeImports: {
        prefer: 'type-imports',
        disallowTypeAnnotations: false,
        fixStyle: 'separate-type-imports',
      },
      methodSignatureStyle: [],
      noMeaninglessVoidOperator: [],
      noUnnecessaryTemplateExpression: [],
      preferAsConst: [],
      noDeprecated: [],
      noDuplicateEnumValues: [],
      noArrayDelete: [],
      noFloatingPromises: {
        ignoreVoid: false,
      },
      noImportTypeSideEffects: [],
    },
  }
}
