import type {Ruleset} from 'lib/unpackRuleset.ts'

const strictImportStyle = (style: 'default' | 'named' | 'namespace' | 'unassigned') => {
  return Object.assign({
    default: false,
    namespace: false,
    named: false,
    unassigned: false,
  }, {
    [style]: true,
  })
}

export const unicornRules = (): Ruleset => ({
  id: 'unicorn',
  warn: {
    noForLoop: [],
    noConsoleSpaces: [],
    preferArraySome: [],
    preferIncludes: [],
    preferModernDomApis: [],
    preferObjectFromEntries: [],
    preferQuerySelector: [],
    preventAbbreviations: {
      replacements: {
        args: false,
        dir: {
          directory: false,
          direction: false,
          folder: true,
        },
        i: {
          index: false,
        },
        opt: {
          option: true,
        },
        props: {
          properties: false,
        },
        pkg: {
          packageJson: true,
        },
      },
    },
    switchCaseBraces: [],
    templateIndent: [],
    catchErrorName: [],
    consistentFunctionScoping: [],
    errorMessage: [],
    escapeCase: [],
    expiringTodoComments: [],
    newForBuiltins: [],
    noArrayForEach: [],
    noAwaitExpressionMember: [],
    noHexEscape: [],
    noNestedTernary: [],
    noNewArray: [],
    noNewBuffer: [],
    noThenable: [],
    noUnnecessaryAwait: [],
    noUselessFallbackInSpread: [],
    noUselessLengthCheck: [],
    noUselessPromiseResolveReject: [],
    noUselessSpread: [],
    noUselessUndefined: [],
    noZeroFractions: [],
    numberLiteralCase: [],
    numericSeparatorsStyle: [],
    preferAddEventListener: [],
    preferArrayFind: [],
    preferArrayFlat: [],
    preferArrayFlatMap: [],
    preferArrayIndexOf: [],
    preferAt: [],
    preferBlobReadingMethods: [],
    preferCodePoint: [],
    preferDateNow: [],
    preferLogicalOperatorOverTernary: [],
    preferMathTrunc: [],
    preferModernMathApis: [],
    preferModule: [],
    preferNativeCoercionFunctions: [],
    preferNegativeIndex: [],
    preferNumberProperties: [],
    preferPrototypeMethods: [],
    preferRegexpTest: [],
    preferSetHas: [],
    preferSetSize: [],
    preferSpread: [],
    preferStringReplaceAll: [],
    preferStringSlice: [],
    preferStringStartsEndsWith: [],
    preferStringTrimStartEnd: [],
    preferTopLevelAwait: [],
    preferTypeError: [],
    relativeUrlStyle: [],
    textEncodingIdentifierCase: [],
    throwNewError: [],
    preferStructuredClone: [],
    noUnnecessarySliceEnd: [],
    preferGlobalThis: [],
    preferMathMinMax: [],
    consistentExistenceIndexCheck: [],
    consistentDateClone: [],
    noInstanceofBuiltins: [],
    noAccessorRecursion: [],
    preferImportMetaProperties: [],
    noUnnecessaryArrayFlatDepth: [],
    noUnnecessaryArraySpliceCount: [],
    preferClassFields: [],
    noArrayReverse: [],
    requireModuleSpecifiers: [],
    noUselessErrorCaptureStackTrace: [],
    preferClasslistToggle: [],
    requireModuleAttributes: [],
    noArraySort: [],
    noUselessCollectionArgument: [],
    preferResponseStaticJson: [],
    importStyle: {
      extendDefaultStyles: false,
      styles: {
        'fs-extra': strictImportStyle('default'),
        'lodash-es': strictImportStyle('namespace'),
      },
    },
    customErrorDefinition: [],
    // no-typeof-undefined
    noTypeofUndefined: [],
    // prefer-bigint-literals
    preferBigintLiterals: [],
    // prefer-string-raw
    preferStringRaw: [],
    // string-content
    stringContent: {
      patterns: {
        ' -> ': '→',
        '\\.\\.\\.': '…',
        "'": '’',
        '°C': '℃',
      },
    },
  },
})
