import type {Ruleset} from '../../../lib/unpackRuleset.ts'

const strictImportStyle = (style: 'default' | 'named' | 'namespace' | 'unassigned') => {
  return {
    default: false,
    namespace: false,
    named: false,
    unassigned: false,
    [style]: true,
  }
}

export const unicornRules = (): Ruleset => {
  return {
    id: 'unicorn',
    warn: {
      noForLoop: [],
      noConsoleSpaces: [],
      preferArraySome: [],
      preferIncludes: [],
      preferModernDomApis: [],
      preferObjectFromEntries: [],
      preferQuerySelector: [],
      nameReplacements: {
        extendDefaultReplacements: false,
        replacements: {
          i: {
            index: false,
          },
        },
      },
      switchCaseBraces: [],
      templateIndent: [],
      catchErrorName: [],
      consistentFunctionScoping: [],
      errorMessage: [],
      escapeCase: [],
      expiringTodoComments: [],
      newForBuiltins: [],
      noForEach: [],
      noAwaitExpressionMember: [],
      preferUnicodeCodePointEscapes: [],
      noNestedTernary: [],
      noNewArray: [],
      noNewBuffer: [],
      noThenable: [],
      noUnnecessaryAwait: [],
      noUselessFallbackInSpread: [],
      noUselessLengthCheck: [],
      noUselessPromiseResolveReject: [],
      noUselessSpread: [],
      noUselessUndefined: [],
      noZeroFractions: [],
      numberLiteralCase: [],
      numericSeparatorsStyle: [],
      preferAddEventListener: [],
      preferArrayFind: [],
      preferArrayFlat: [],
      preferArrayFlatMap: [],
      preferArrayIndexOf: [],
      preferAt: [],
      preferBlobReadingMethods: [],
      preferCodePoint: [],
      preferDateNow: [],
      preferLogicalOperatorOverTernary: [],
      preferMathTrunc: [],
      preferModernMathApis: [],
      preferModule: [],
      preferNativeCoercionFunctions: [],
      preferNegativeIndex: [],
      preferNumberProperties: [],
      preferPrototypeMethods: [],
      preferRegexpTest: [],
      preferSetHas: [],
      preferSetSize: [],
      preferSpread: [],
      preferStringReplaceAll: [],
      preferStringSlice: [],
      preferStringStartsEndsWith: [],
      preferStringTrimStartEnd: [],
      preferTopLevelAwait: [],
      preferTypeError: [],
      relativeUrlStyle: [],
      textEncodingIdentifierCase: [],
      throwNewError: [],
      preferStructuredClone: [],
      noUnnecessarySliceEnd: [],
      preferGlobalThis: [],
      preferMathMinMax: [],
      consistentExistenceIndexCheck: [],
      consistentDateClone: [],
      noInstanceofBuiltins: [],
      noAccessorRecursion: [],
      preferImportMetaProperties: [],
      noUnnecessaryArrayFlatDepth: [],
      noUnnecessaryArraySpliceCount: [],
      preferClassFields: [],
      noArrayReverse: [],
      requireModuleSpecifiers: [],
      noUselessErrorCaptureStackTrace: [],
      preferClasslistToggle: [],
      requireModuleAttributes: [],
      noArraySort: [],
      noUselessCollectionArgument: [],
      preferResponseStaticJson: [],
      importStyle: {
        extendDefaultStyles: false,
        styles: {
          'fs-extra': strictImportStyle('default'),
          zod: strictImportStyle('default'),
        },
      },
      customErrorDefinition: [],
      noTypeofUndefined: [],
      preferBigintLiterals: [],
      preferStringRaw: [],
      consistentTemplateLiteralEscape: [],
      noUselessIteratorToArray: [],
      switchCaseBreakPosition: [],
    },
  }
}
