import type {Ruleset} from '../../../lib/unpackRuleset.ts'

export const zodRules = (): Ruleset => ({
  id: 'zod',
  warn: {
    arrayStyle: [],
    noAnySchema: [],
    noCoerceBoolean: [],
    noConflictingChecks: [],
    noDuplicateSchemaMethods: [],
    noEmptyCustomSchema: [],
    noNativeEnum: [],
    noNumberSchemaWithFinite: [],
    noNumberSchemaWithInt: [],
    noNumberSchemaWithIsFinite: [],
    noNumberSchemaWithIsInt: [],
    noNumberSchemaWithSafe: [],
    noNumberSchemaWithStep: [],
    noOptionalAndDefaultTogether: [],
    noPromiseSchema: [],
    noSchemaWithIsNullable: [],
    noSchemaWithIsOptional: [],
    noThrowInRefine: [],
    noTransformInRecordKey: [],
    noUnnecessaryReadonly: [],
    preferEnumOverLiteralUnion: [],
    preferLooseObject: [],
    preferMapSetSizeOverMinMax: [],
    preferMetaLast: [],
    preferNullish: [],
    preferStrictObject: [],
    preferStringLengthOverMinMax: [],
    preferTopLevelStringFormats: [],
    preferTrimBeforeStringLengthChecks: [],
    preferValidate: [],
    requireBrandTypeParameter: [],
    requireErrorMessage: [],
  },
})
