import type {Ruleset} from '../../../lib/unpackRuleset.ts'

export const packageJsonRules = (): Ruleset => {
  return {
    id: 'package-json',
    warn: {
      binNameCasing: [],
      repositoryShorthand: [],
      preferRollingWorkspaceSpec: [],
      restrictDependencyRanges: {
        forDependencyTypes: ['dependencies', 'devDependencies', 'optionalDependencies'],
        rangeType: 'pin',
      },
      scriptsNameCasing: [],
      specifyPeersLocally: [],
      uniqueDependencies: [],
      requireName: [],
      requireType: [],
      requireVersion: [],
      requireDescription: [],
      'valid-author': [],
      'valid-bin': [],
      'valid-browser': [],
      'valid-bugs': [],
      'valid-bundleDependencies': [],
      'valid-config': [],
      'valid-contributors': [],
      'valid-cpu': [],
      'valid-dependencies': [],
      'valid-description': [],
      'valid-devDependencies': [],
      'valid-devEngines': [],
      'valid-directories': [],
      'valid-engines': [],
      'valid-exports': [],
      'valid-files': [],
      'valid-funding': [],
      'valid-gypfile': [],
      'valid-homepage': [],
      'valid-keywords': [],
      'valid-libc': [],
      'valid-license': [],
      'valid-main': [],
      'valid-man': [],
      'valid-module': [],
      'valid-name': [],
      'valid-optionalDependencies': [],
      'valid-os': [],
      'valid-packageManager': [],
      'valid-peerDependencies': [],
      'valid-peerDependenciesMeta': [],
      'valid-peerDependenciesMeta-relationship': [],
      'valid-private': [],
      'valid-publishConfig': [],
      'valid-repository': [],
      'valid-repository-directory': [],
      'valid-scripts': [],
      'valid-sideEffects': [],
      'valid-type': [],
      'valid-version': [],
      'valid-workspaces': [],
    },
  }
}
