plugins:
- n
- promise
- unicorn
- i
- simple-import-sort
- import-quotes
- '@typescript-eslint'
- regexp
- perfectionist
- jsonc
- yml
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: true
env:
  node: true
  shared-node-browser: true
settings:
  import/parsers:
    '@typescript-eslint/parser':
    - '*.ts'
    - '*.tsx'
  import/resolver:
    typescript:
      alwaysTryTypes: true
    node: true
ignorePatterns:
- /../../dist/
- /../../out/
- /../../temp/
- /../../srcCompiled/
- /../../srcCompiled-*/
- '*.d.ts'
- node_modules/
overrides:
- files:
  - '*.ts'
  - '*.js'
  - '*.tsx'
  - '*.jsx'
  parser: '@typescript-eslint/parser'
- files:
  - '*.json'
  - '*.json5'
  - '*.jsonc'
  parser: jsonc-eslint-parser
- files:
  - '*.yml'
  - '*.yaml'
  parser: yaml-eslint-parser
