plugins:
  - node
  - promise
  - unicorn
  - import
  - simple-import-sort
  - import-quotes
  - "@typescript-eslint"
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: true
globals:
  GOOGLE_ANALYTICS_TRACKING_ID: "readonly"
  __non_webpack_require__: "readonly"
env:
  node: true
  shared-node-browser: true
