plugins:
  - 'n'
  - promise
  - unicorn
  - i
  - simple-import-sort
  - import-quotes
  - "@typescript-eslint"
  - regexp
  - package-json
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: true
env:
  node: true
  shared-node-browser: true
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
  import/resolver:
    typescript:
      alwaysTryTypes: true
    node: true
ignorePatterns:
  - /dist/
  - /out/
  - /temp/
  - /srcCompiled/
  - /srcCompiled-*/
  - '*.d.ts'
  - node_modules/
