plugins:
  - 'n'
  - promise
  - unicorn
  - i
  - simple-import-sort
  - import-quotes
  - "@typescript-eslint"
  - regexp
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: true
globals:
  GOOGLE_ANALYTICS_TRACKING_ID: "readonly"
  __non_webpack_require__: "readonly"
env:
  node: true
  shared-node-browser: true
settings:
  import/parsers:
    '@typescript-eslint/parser': [.ts]
  import/resolver:
    typescript:
      alwaysTryTypes: true
