name: buildHtml
on:
  push:
    branches: [main]
permissions:
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3
      - name: setupNode
        uses: actions/setup-node@v3.7.0
        with:
          node-version: latest
      - name: npm install
        uses: jaid/action-npm-install@main
      - id: build
        name: build
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: buildPage
        name: buildPage
        run: npm run buildPage
      - name: check
        id: check
        shell: bash
        working-directory: ${{ github.workspace }}/dist/page
        run: ls -l --almost-all --color=always --si --literal --group-directories-first
      - name: Setup Pages
        id: setupPages
        uses: actions/configure-pages@v3.0.6
      - name: uploadPages
        id: uploadPages
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: '${{ github.workspace }}/dist/page'
      - name: deployPages
        id: deployPages
        uses: actions/deploy-pages@v2.0.4
